name: Docker Image CI - DEV

on: 
  push:
    branches-ignore:
      - master

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image & Publish to Registry
      env:
        SHA8: ${GITHUB_SHA::8}
        GITHUB_REPOSITORY: ${{ github.repository }}
      uses: docker/build-push-action@v3
      with:
        context: .
        tags: "ghcr.io/ivivanov-bg/portfolio-docker:dev"
        platforms: linux/amd64, linux/arm64
        push: true
